all:
	echo "Test $(toupper hello world)"
	echo "Test $(tolower HELLO WORLD)"
	echo "$(calc  (1 + 3) )"
	echo "$(calc  (2<3 ? 3 : 2) * 10 )"
	echo "NJOBS_SLOTS=${MAKE_JOB_SLOTS}"
	echo "$(md5 hello world)"
	echo "${MACHINE_PROCESSORS}"
	echo "${MACHINE_CORES}"
	echo "$(dichotomyl 1 2 3 4 5 6 7 8 9 10 11)"
	echo "$(dichotomyr 1 2 3 4 5 6 7 8 9 10 11)"
	echo "$(sublist 1 2 3 4 5 6 7 8 9 10 11)"
	echo "$(sublist 1 2 3 4 5 6 7 8 9 10 11,5)"
	echo "$(sublist 1 2 3 4 5 6 7 8 9 10 11,)"
	echo "$(sublist 1 2 3 4 5 6 7 8 9 10 11,1,3)"
	echo "$(sublist 1 2 3 4 5 6 7 8 9 10 11,,3)"
	echo "$(sublist 1 2 3 4 5 6 7 8 9 10 11,1000,3)"
	

